/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Question = {
  _id: string;
  _type: "question";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text: InternationalizedArrayText;
  category: CategoryReference;
  answers: Array<{
    text: InternationalizedArrayString;
    _type: "answer";
    _key: string;
  }>;
  correctAnswerIndex: number;
  explanation?: InternationalizedArrayText;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type InternationalizedArrayText = Array<{
  _key: string;
} & InternationalizedArrayTextValue>;

export type InternationalizedArrayString = Array<{
  _key: string;
} & InternationalizedArrayStringValue>;

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: InternationalizedArrayString;
  slug: Slug;
  description?: InternationalizedArrayText;
  parent?: CategoryReference;
  color?: string;
  icon?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order?: number;
  timeLimit?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = CategoryReference | SanityImageAssetReference | Question | SanityImageCrop | SanityImageHotspot | InternationalizedArrayText | InternationalizedArrayString | Category | Slug | InternationalizedArrayTextValue | InternationalizedArrayStringValue | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && !defined(parent)] | order(order asc) {		_id,		"title": coalesce(title[_key == $locale][0].value, title[_key == "en"][0].value),		"slug": slug.current,		"description": coalesce(description[_key == $locale][0].value, description[_key == "en"][0].value),		color,		icon,		image {			asset-> {				_id,				url			}		},		order	}
export type CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string;
  description: string | null;
  color: string | null;
  icon: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  order: number | null;
}>;
// Variable: SUBCATEGORIES_QUERY
// Query: *[_type == "category" && parent._ref == $parentId] | order(order asc) {		_id,		"title": coalesce(title[_key == $locale][0].value, title[_key == "en"][0].value),		"slug": slug.current,		"description": coalesce(description[_key == $locale][0].value, description[_key == "en"][0].value),		parent-> {			_id,			"title": coalesce(title[_key == $locale][0].value, title[_key == "en"][0].value)		},		color,		icon,		image {			asset-> {				_id,				url			}		},		order	}
export type SUBCATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string;
  description: string | null;
  parent: {
    _id: string;
    title: string | null;
  } | null;
  color: string | null;
  icon: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  order: number | null;
}>;
// Variable: QUESTIONS_BY_CATEGORY_QUERY
// Query: *[_type == "question" && category._ref == $categoryId] {		_id,		"text": coalesce(text[_key == $locale][0].value, text[_key == "en"][0].value),		category-> {			_id,			"title": coalesce(title[_key == $locale][0].value, title[_key == "en"][0].value),			timeLimit		},		"answers": answers[] {			_key,			"text": coalesce(text[_key == $locale][0].value, text[_key == "en"][0].value)		},		correctAnswerIndex,		"explanation": coalesce(explanation[_key == $locale][0].value, explanation[_key == "en"][0].value),		image {			asset-> {				_id,				url			}		}	}
export type QUESTIONS_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  text: string | null;
  category: {
    _id: string;
    title: string | null;
    timeLimit: number | null;
  };
  answers: Array<{
    _key: string;
    text: string | null;
  }>;
  correctAnswerIndex: number;
  explanation: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: ALL_CATEGORY_IDS_QUERY
// Query: *[_type == "category"]._id
export type ALL_CATEGORY_IDS_QUERYResult = Array<string>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n\t*[_type == \"category\" && !defined(parent)] | order(order asc) {\n\t\t_id,\n\t\t\"title\": coalesce(title[_key == $locale][0].value, title[_key == \"en\"][0].value),\n\t\t\"slug\": slug.current,\n\t\t\"description\": coalesce(description[_key == $locale][0].value, description[_key == \"en\"][0].value),\n\t\tcolor,\n\t\ticon,\n\t\timage {\n\t\t\tasset-> {\n\t\t\t\t_id,\n\t\t\t\turl\n\t\t\t}\n\t\t},\n\t\torder\n\t}\n": CATEGORIES_QUERYResult;
    "\n\t*[_type == \"category\" && parent._ref == $parentId] | order(order asc) {\n\t\t_id,\n\t\t\"title\": coalesce(title[_key == $locale][0].value, title[_key == \"en\"][0].value),\n\t\t\"slug\": slug.current,\n\t\t\"description\": coalesce(description[_key == $locale][0].value, description[_key == \"en\"][0].value),\n\t\tparent-> {\n\t\t\t_id,\n\t\t\t\"title\": coalesce(title[_key == $locale][0].value, title[_key == \"en\"][0].value)\n\t\t},\n\t\tcolor,\n\t\ticon,\n\t\timage {\n\t\t\tasset-> {\n\t\t\t\t_id,\n\t\t\t\turl\n\t\t\t}\n\t\t},\n\t\torder\n\t}\n": SUBCATEGORIES_QUERYResult;
    "\n\t*[_type == \"question\" && category._ref == $categoryId] {\n\t\t_id,\n\t\t\"text\": coalesce(text[_key == $locale][0].value, text[_key == \"en\"][0].value),\n\t\tcategory-> {\n\t\t\t_id,\n\t\t\t\"title\": coalesce(title[_key == $locale][0].value, title[_key == \"en\"][0].value),\n\t\t\ttimeLimit\n\t\t},\n\t\t\"answers\": answers[] {\n\t\t\t_key,\n\t\t\t\"text\": coalesce(text[_key == $locale][0].value, text[_key == \"en\"][0].value)\n\t\t},\n\t\tcorrectAnswerIndex,\n\t\t\"explanation\": coalesce(explanation[_key == $locale][0].value, explanation[_key == \"en\"][0].value),\n\t\timage {\n\t\t\tasset-> {\n\t\t\t\t_id,\n\t\t\t\turl\n\t\t\t}\n\t\t}\n\t}\n": QUESTIONS_BY_CATEGORY_QUERYResult;
    "\n\t*[_type == \"category\"]._id\n": ALL_CATEGORY_IDS_QUERYResult;
  }
}
